[package]
name = "snsx-network-stack"
version.workspace = true
edition.workspace = true

[dependencies]
aes-gcm-siv.workspace = true
anyhow.workspace = true
base64.workspace = true
ed25519-dalek.workspace = true
rand_core.workspace = true
serde.workspace = true
sha3.workspace = true
x25519-dalek.workspace = true

